### ISSUE TITLE
Week 12: Adding functionality for volume & disfluency detection and start checking rhythm

### ISSUE THREAD

**Issue by Tlewis10** [gw-sd-2016/Presenting101#2]
@twood02 @cctoombs With this issue I have added functionality for what will be the beginnings of the user error report (UER). This UER in the helloworld class is for the disfluency checker. I have also been playing with “token” which give time stamps of the words said this will be part of the rhythm detection. It counts and delivers bad word count. For the volume detector the UER shows the average volume of the speaker throughout the course of their presentation.

**Comment by twood02** [comment]
sounds good. keep it up!

I've adjusted your week numbering scheme--think of this as an end-of-week report rather than the start of a week.
