### ISSUE TITLE
Week 13: Able to detect rhythm of user by finding wps

### ISSUE THREAD

**Issue by Tlewis10** [gw-sd-2016/Presenting101#3]
@twood02 @cctoombs This week, sticking with my schedule, I have been working on “detecting” the rhythm of speakers. The code that I have committed seems relatively basic but it took a lot of doing to get it working. It also is my third iteration of trying to get rhythm. Initially I tried using the same library that I used for disfluency detection (Sphinx) but it was only working given a set grammar. Next I thought about using IBM’s Watson and taking that data which is outputted as a JSON file. By doing this I wrote a program to parse that JSON file and check for time stamps but I decided that I did not want to rely on any outside programs. As a result I went back to the Sphinx library and found that CMU posted a more up to date version that would allow me to detect words and time stamps. The committed code takes in words (not based on any grammars but rather a language) spoken, gets the time stamp and I have begun checking time stamps against what is appropriate speaking rates and the program takes note of when it goes out of that range.

**Comment by twood02** [comment]
excellent.  Using the sphinx library sounds like a better solution that watson.  Glad you found a way to get it to work.
